### ISSUE TITLE
Document specific content

### ISSUE THREAD

**Issue by wrynearson** [earth-genome/foodtwin-global-app#28]
The purpose of this document is to supply real data examples that will help create high-fidelity mockups for the application, to be sure everyone is aligned on the content and metrics being used.

The document outlines three user journeys: producing area; shipping route and shipping node. To easily navigate and identify the relevant sections, please open the document outline on the left, as the content repeats for each journey.

**Comment by faustoperez** [comment]
Link to the content document 👉 https://docs.google.com/document/d/1LWeH9XVO4r9H5t7ay6MwIxWHENfcsjuqmc_XgnLFjZc/edit?usp=sharing

### Instructions

Select a representative data point for each user journey as your starting point and try to fill in the information as completely as possible using real data. Edit the red fields in the tables below or leave comments on the document as necessary.
As a tip, when inputting content, please consider worst-case scenarios such as long figures, extremely short or long names, or missing data.
