### ISSUE TITLE
Bathymetry base layer

### ISSUE THREAD

**Issue by vgeorge** [earth-genome/foodtwin-global-app#42]
The base map styles for the land mass should include a bathymethy layer. 

cc @oliverroick @faustoperez

**Comment by oliverroick** [comment]
@faustoperez to move the layer to DevSeed Mapbox account

**Comment by faustoperez** [comment]
This is to confirm I have moved the styles to the DevSeed Mapbox account. I have removed the roads but kept the admin boundaries, let me know if anything else is needed 👍
