### ISSUE TITLE
Socioeconomic indicators for areas panels

### ISSUE THREAD

**Issue by vgeorge** [earth-genome/foodtwin-global-app#43]
The area panels should include key socioeconomic indicators for areas. Some initial questions:

- Are we going to display indicators for national areas?
- Which indicators do we want to display? 
- Is the data available to be ingested?

cc @cameronkruse @kushankb @faustoperez

**Comment by oliverroick** [comment]
Data: https://drive.google.com/drive/folders/1eVn10NsKxjTpMiOYBTdmDkhuL-oOX8ZO
