### ISSUE TITLE
Empty state for area view

### ISSUE THREAD

**Issue by vgeorge** [earth-genome/foodtwin-global-app#85]
If an area doesn't produce any food or if no data is available, the side panel should display an empty state.

We don't expect many areas to fall into this category, so a simple, centered message on the page should suffice:

```
There is no food produced in this area or no data is available.
```

cc @oliverroick @faustoperez

**Comment by faustoperez** [comment]
Good call @vgeorge, here's a quick mockup for the empty state:

Figma 👉 https://www.figma.com/design/zz7755JriAt4vKJsdV3Dcr/Global-Food-Twin?node-id=1658-4077&t=UoYlYjO4LnnBbiET-1

![Image](https://github.com/user-attachments/assets/98663701-2162-49cf-b310-97647233bec9)
